name: Docs

on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: gitconfig
      run: |
        git config --global user.email automate@hanazuki.dev
        git config --global user.name automate
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: recursive
        persist-credentials: true
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install
      run: npm ci
    - name: Generate docs
      run: scripts/generate-docs.sh
