name: Docs

on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: gitconfig
      run: |
        git config --global user.email automate@hanazuki.dev
        git config --global user.name automate
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: recursive
        persist-credentials: true
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install
      run: npm ci
    - name: Generate docs
      run: scripts/generate-docs.sh
