name: Docs

on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: gitconfig
      run: |
        git config --global user.email automate@hanazuki.dev
        git config --global user.name automate
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        persist-credentials: false
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install
      run: npm ci
    - name: Generate docs
      run: scripts/generate-docs.sh
